### ISSUE TITLE
Compact Version

### ISSUE THREAD

**Issue by LouisPi** [dalymople/DeadReckoner#1]
Hello,
Where can I find more information on the compact version?
Thanks in advance,
Louis

**Comment by dalymople** [comment]
Hi,
Sorry this is work in progress! The compact boards are complete, I just have not finished updating the docs. Will be done asap.
Thanks,
Alex

**Comment by LouisPi** [comment]
> Hi,
> Sorry this is work in progress! The compact boards are complete, I just have not finished updating the docs. Will be done asap.
> Thanks,
> Alex

Okay, sounds good! Will you be selling the compact boards on Tindie?

Thanks,
Louis

**Comment by dalymople** [comment]
Ok, docs have been updated and the modules are listed on Tindie :)
Issue closed.
