### ISSUE TITLE
Cannot find the dimensions of the compact module

### ISSUE THREAD

**Issue by steph643** [dalymople/DeadReckoner#2]
The home page says dimensions are 65mm x 35mm. I guess this is for the original version. What are the dimensions of the compact one?

**Comment by dalymople** [comment]
Hi @steph643,
Good point, the compact module is 52mm x 36.5mm.
I'll add dimensioned drawings into the repo.

**Comment by dalymople** [comment]
@steph643 new folder added with mechanical drawings and DXF files.

**Comment by steph643** [comment]
Thanks a lot. 
I would like to order one. Is https://www.tindie.com/ your only resseller?

**Comment by dalymople** [comment]
@steph643 yes. But I do sell direct for custom boards and bulk orders.
Feel free to shoot me an email to discus.

**Comment by steph643** [comment]
Thanks @dalymople. I must be dumb but I cannot seem to find your email address :-) Please reach me at [steve.colbow@gmail.com](mailto:steve.colbow@gmail.com).
